# Generated by Django 5.2.13 on 2026-04-30 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='bi-brain', max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('task_type', models.CharField(choices=[('visual', 'Визуальная память'), ('text', 'Текстовая память'), ('number', 'Числовая память'), ('pattern', 'Запоминание паттернов')], max_length=20, verbose_name='Тип задания')),
                ('difficulty', models.IntegerField(choices=[(1, 'Лёгкий'), (2, 'Средний'), (3, 'Сложный')], default=1, verbose_name='Сложность')),
                ('task_data', models.JSONField(default=dict, verbose_name='Данные задания')),
                ('base_points', models.IntegerField(default=10, verbose_name='Базовые очки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('score', models.IntegerField(default=0, verbose_name='Набранные очки')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('attempts', models.IntegerField(default=1, verbose_name='Попытки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
