# Generated by Django 5.2.13 on 2026-05-04 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор')),
                ('category', models.CharField(choices=[('visual', 'Визуальная память'), ('number', 'Числовая память'), ('text', 'Текстовая память')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('instruction', models.TextField(verbose_name='Инструкция для пользователя')),
                ('icon', models.CharField(default='bi-puzzle', max_length=50, verbose_name='Иконка')),
                ('generator_class', models.CharField(max_length=100, verbose_name='Класс генератора')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип упражнения',
                'verbose_name_plural': 'Типы упражнений',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedTextCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('questions', models.JSONField(verbose_name='Вопросы и ответы')),
                ('difficulty', models.IntegerField(verbose_name='Сложность')),
                ('used_count', models.IntegerField(default=0, verbose_name='Сколько раз использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кэш текста с вопросами',
                'verbose_name_plural': 'Кэш текстов с вопросами',
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('score', models.IntegerField(default=0, verbose_name='Начисленные очки')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('details', models.JSONField(default=dict, verbose_name='Детали')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.exercisetype', verbose_name='Тип упражнения')),
            ],
            options={
                'verbose_name': 'Сессия упражнения',
                'verbose_name_plural': 'Сессии упражнений',
                'ordering': ['-started_at'],
            },
        ),
    ]
