# Generated by Django 5.2.13 on 2026-05-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_exercisetype_generatedtextcache_exercisesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedtextcache',
            name='last_used',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее использование'),
        ),
        migrations.AlterField(
            model_name='generatedtextcache',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Лёгкий'), (2, 'Средний'), (3, 'Сложный')], verbose_name='Сложность'),
        ),
    ]
