# Generated by Django 5.2.13 on 2026-05-29 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_generatedtextcache_last_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='bi-trophy-fill', max_length=50, verbose_name='Иконка')),
                ('condition_type', models.CharField(choices=[('tasks_completed', 'Выполнено заданий'), ('perfect_tasks', 'Заданий без ошибок'), ('level_reached', 'Достигнут уровень'), ('points_total', 'Всего очков опыта'), ('specific_task_perfect', 'Конкретное задание без ошибок'), ('hard_difficulty_task', 'Задание на высокой сложности'), ('specific_task_hard', 'Конкретное задание на высокой сложности')], max_length=50, verbose_name='Тип условия')),
                ('condition_value', models.IntegerField(verbose_name='Значение условия')),
                ('condition_extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Доп. параметр')),
                ('reward_points', models.IntegerField(default=0, verbose_name='Награда (опыт)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
