# Generated by Django 5.2.13 on 2026-05-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_achievement_userachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='condition_extra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительный параметр'),
        ),
    ]
